### ISSUE TITLE
Include option to launch all applications (locations, sizes, workspaces) after reboot

### ISSUE THREAD

**Issue by zanovis** [khimaros/smart-auto-move#17]
This could be a nice way to 'preserve' your workspaces after a necessary reboot.

**Comment by khimaros** [comment]
previously requested in https://github.com/khimaros/smart-auto-move/issues/1 -- i'm going to pin this issue since it is a common request

for now, i consider this is out of scope for Smart Auto Move and better handled by https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager -- it's best to do one thing really well!

i'd like to explore opportunities for tighter integration between these two extensions as mentioned in https://github.com/khimaros/smart-auto-move/issues/5
